{% set name = "napari-annotator" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_annotator-{{ version }}.tar.gz
  sha256: 15177d50d820c22afc5f70c7d02e4ef56f7ed52a1453c2c692eb488beb2beb7f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - napari
    - numpy
    - python >=3.7
    - scikit-image

test:
  imports:
    - napari_annotator
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/loicsauteur/napari-annotator
  summary: A lightweight plugin extending label layer control
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - loicsauteur
